### ISSUE TITLE
BP-2694 Config serialization on Adobe Commerce 2.4.5-p3

### ISSUE THREAD

**Issue by gustavorof** [buckaroo-it/Magento2_Analytics#22]
When upgrade Adobe Commerce to 2.4.5-p3, I started having this error on order placement:

TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in /home/gustavo/development/smartphonehoesjes-magento-2/vendor/magento/framework/Serialize/Serializer/Json.php:42
Stack trace:
#0 /home/gustavo/development/smartphonehoesjes-magento-2/vendor/magento/framework/Serialize/Serializer/Json.php(42): json_decode()
#1 /home/gustavo/development/smartphonehoesjes-magento-2/vendor/buckaroo/magento2analytics/Model/ConfigProvider/Analytics.php(51): Magento\Framework\Serialize\Serializer\Json->unserialize()

When checking the config: buckaroo_magento2/analytics/cookie_param_pair I have a valid serialized (Even values coming from config.xml) and getValue() function of \Buckaroo\Magento2Analytics\Model\ConfigProvider\Analytics::getCookieParamPairs() is already returning an array.

I cannot reproduce this behavior on previous version of Adobe Commerce (<= 2.4.5-p2).

**Comment by Buckaroo-Rens** [comment]
Thanks @gustavorof for mentioning, we will look into your PR a.s.a.p.

**Comment by Buckaroo-Rens** [comment]
Fixed with PR from @gustavorof, will be included in upcoming release!
